FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:12

WORKDIR /usr/src/app

COPY ./app/ /usr/src/app/

# Install dependencies
RUN  rm -rf /usr/src/app/node_modules
RUN JOBS=MAX npm install --production && rm -rf /tmp/*


EXPOSE 8080

CMD ["npm", "start"]
