version: '2'
volumes:
    tele-data:
    settings:
services: 
    tesla:
        restart: always
        privileged: true
        build: ./tesla
        depends_on:
            - browser
        ports:
            - 8080:8080  #external:internal
        
    
    browser:
        restart: always
        image: balenablocks/browser
        network_mode: host
        privileged: true
        volumes:
            - 'settings:/data'

    wifi-connect:
        build: ./wifi-connect
        restart: always
        network_mode: host
        privileged: true
        labels:
            io.balena.features.dbus: '1'
            io.balena.features.firmware: '1'